# Generated by Django 4.2.29 on 2026-03-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('volume_type', models.CharField(choices=[('single', 'Единичный'), ('multiple', 'Множественный')], max_length=20, verbose_name='Тип объема заказа')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Описание')),
                ('document', models.FileField(blank=True, null=True, upload_to='orders/%Y/%m/%d/', verbose_name='Документ')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Указывается для множественного заказа', verbose_name='Количество')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('processing', 'Обрабатывается'), ('assembling', 'Собирается'), ('delivering', 'Доставляется'), ('ready', 'Готов')], default='created', max_length=20, verbose_name='Статус')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата готовности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
    ]
